import {StyleSheet} from 'react-native';
import {COLORS} from '../../constants/theme';
import {convertPX, height, width} from '../../utils';

export default StyleSheet.create({
  root: {
    width: width,
    minHeight: height,
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },

  subtitle: {
    color: '#080D45',
    fontWeight: '700',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Muslin',
    width: convertPX(227),
    height: convertPX(36),
    fontSize: convertPX(24),
    lineHeight: convertPX(36),
    marginVertical: convertPX(5),
    letterSpacing: convertPX(0.9),
  },
  dotWrap: {
    display: 'flex',
    marginBottom: 0,
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    width: convertPX(152),
    justifyContent: 'center',
    marginVertical: convertPX(15),
  },
  dot: {
    borderWidth: 1.2,
    width: convertPX(24),
    height: convertPX(24),
    borderColor: COLORS.blue,
    borderRadius: convertPX(20),
    marginHorizontal: convertPX(3),
    backgroundColor: COLORS.primary,
  },

  heroWrap: {
    alignSelf: 'center',
    alignItems: 'center',
    width: convertPX(327),
    marginVertical: convertPX(35),
    justifyContent: 'center',
  },
  heroText: {
    color: '#080D45',
    fontFamily: 'Muslin',
    position: 'absolute',
    fontSize: convertPX(10),
    lineHeight: convertPX(21),
    letterSpacing: convertPX(0.9),
  },
  image: {
    alignSelf: 'center',
    position: 'relative',
    width: convertPX(180),
    height: convertPX(180),
    marginVertical: convertPX(40),
  },

  // text: {
  //   color: '#000',
  //   fontWeight: '400',
  //   textAlign: 'center',
  //   fontFamily: 'Muslin',
  //   height: convertPX(18),
  //   fontSize: convertPX(14),
  //   lineHeight: convertPX(17.57),
  //   marginVertical: convertPX(18),
  //   letterSpacing: convertPX(0.9),
  //   marginHorizontal: convertPX(20),
  // },

  outcomeWrap: {
    width: convertPX(327),
    marginBottom: convertPX(120),
    marginHorizontal: convertPX(20),
  },
  outcomeTitleWrap: {
    width: convertPX(174),
    backgroundColor: '#FBFAFA',
    marginBottom: convertPX(5),
    borderRadius: convertPX(6),
    paddingVertical: convertPX(15),
    paddingHorizontal: convertPX(5),
  },
  outcomeTitle: {
    color: '#4B4B4B',
    fontWeight: '700',
    fontFamily: 'Muslin',
    fontSize: convertPX(14),
    lineHeight: convertPX(21),
    backgroundColor: '#FBFAFA',
    marginBottom: convertPX(3),
    letterSpacing: convertPX(0.9),
    paddingHorizontal: convertPX(5),
  },
  outcomeSubTitle: {
    color: '#666666',
    fontWeight: '700',
    fontFamily: 'Muslin',
    fontSize: convertPX(12),
    lineHeight: convertPX(18),
    backgroundColor: '#FBFAFA',
    letterSpacing: convertPX(0.9),
    paddingHorizontal: convertPX(5),
  },
  outcomeItems: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    width: convertPX(327),
    height: convertPX(65),
    borderRadius: convertPX(6),
    backgroundColor: '#F7F7F7',
    marginVertical: convertPX(5),
    paddingVertical: convertPX(2),
    justifyContent: 'space-between',
    paddingHorizontal: convertPX(5),
  },
  outcomeText: {
    color: '#080D45',
    fontWeight: '600',
    fontFamily: 'Muslin',
    fontSize: convertPX(14),
    paddingTop: convertPX(5),
    lineHeight: convertPX(18),
    paddingHorizontal: convertPX(5),
  },
  ellipseWrap: {
    width: convertPX(32),
    height: convertPX(32),
    justifyContent: 'center',
  },
  ellipseBg: {
    position: 'absolute',
  },
  ellipse: {
    right: 0,
    bottom: 0,
    position: 'absolute',
  },
  ellipseText: {
    color: '#243B80',
    fontWeight: '800',
    alignSelf: 'center',
    position: 'absolute',
    fontSize: convertPX(8),
  },
  button: {
    alignItems: 'center',
    width: convertPX(327),
    height: convertPX(50),
    justifyContent: 'center',
    marginTop: convertPX(15),
    borderRadius: convertPX(6),
    backgroundColor: '#C2C7FF',
  },
  buttonText: {
    color: COLORS.black,
    fontSize: convertPX(16),
  },
});
