import {StyleSheet} from 'react-native';
import {COLORS} from '../../constants/theme';
import {convertPX, height, width} from '../../utils';

const topSize = 60;

export default StyleSheet.create({
  root: {
    width: width,
    minHeight: height,
    alignItems: 'center',
    backgroundColor: COLORS.primary,
  },

  subtitle: {
    color: '#4B4B4B',
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Muslin',
    width: convertPX(221),
    height: convertPX(30),
    fontSize: convertPX(20),
    lineHeight: convertPX(30),
    marginVertical: convertPX(5),
  },

  heroWrap: {
    marginTop: 5,
    alignItems: 'center',
    width: convertPX(326),
    height: convertPX(173),
    borderRadius: convertPX(5),
    backgroundColor: COLORS.purple,
    marginVertical: convertPX(10),
  },
  heroBIcon: {
    opacity: 0.9,
    position: 'absolute',
    width: convertPX(topSize),
    height: convertPX(topSize),
    backgroundColor: '#B274E2',
  },
  heroIIcon: {
    position: 'absolute',
    width: convertPX(topSize - 20),
    height: convertPX(topSize - 20),
    backgroundColor: COLORS.purple,
  },

  heroTitle: {
    marginTop: '7%',
    color: '#FFFFFF',
    fontWeight: '500',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Muslin',
    width: convertPX(204),
    height: convertPX(50),
    fontSize: convertPX(40),
    lineHeight: convertPX(50),
    letterSpacing: convertPX(2),
  },
  heroText: {
    marginTop: '1%',
    color: '#FFFFFF',
    textAlign: 'center',
    alignSelf: 'center',
    fontFamily: 'Muslin',
    width: convertPX(101),
    fontSize: convertPX(16),
    lineHeight: convertPX(20),
    letterSpacing: convertPX(1),
  },
  heroBtn: {
    alignItems: 'center',
    width: convertPX(92),
    height: convertPX(34),
    justifyContent: 'center',
    borderRadius: convertPX(6),
    backgroundColor: COLORS.primary,
  },
  heroBtnText: {
    color: '#4B4B4B',
    textAlign: 'center',
    fontFamily: 'Muslin',
    fontSize: convertPX(12),
    letterSpacing: convertPX(1),
  },

  dotWrap: {
    display: 'flex',
    alignSelf: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    width: convertPX(56),
    justifyContent: 'center',
    marginVertical: convertPX(10),
  },
  dot: {
    borderWidth: 1,
    width: convertPX(8),
    height: convertPX(8),
    borderColor: COLORS.purple,
    borderRadius: convertPX(20),
    backgroundColor: COLORS.purple,
    marginHorizontal: convertPX(3),
  },
  iconWrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: convertPX(20),
    justifyContent: 'space-between',
  },
  icon: {
    width: convertPX(40),
    height: convertPX(40),
  },
  iconText: {
    color: '#000',
    fontWeight: '600',
    fontFamily: 'Muslin',
    height: convertPX(17),
    fontSize: convertPX(12),
    maxWidth: convertPX(109),
    lineHeight: convertPX(15),
    marginVertical: convertPX(10),
  },

  optionWrap: {
    width: convertPX(327),
    height: convertPX(270),
    backgroundColor: '#F4F4F4',
    borderRadius: convertPX(6),
    marginVertical: convertPX(10),
  },
  optionItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: convertPX(1),
    justifyContent: 'space-between',
    paddingHorizontal: convertPX(10),
  },
  optionText: {
    color: '#000',
    fontWeight: '600',
    fontFamily: 'Muslin',
    height: convertPX(18),
    fontSize: convertPX(14),
    lineHeight: convertPX(18),
    marginVertical: convertPX(18),
    letterSpacing: convertPX(0.9),
  },

  optionIconWrap: {flexDirection: 'row', alignItems: 'center'},

  optionIconText: {
    color: '#7F18D0',
    fontWeight: '600',
    fontFamily: 'Muslin',
    height: convertPX(18),
    fontSize: convertPX(14),
    lineHeight: convertPX(18),
    marginVertical: convertPX(18),
    letterSpacing: convertPX(0.9),
  },

  recentWrap: {
    width: convertPX(327),
    paddingHorizontal: convertPX(2),
    marginVertical: convertPX(35),
  },
  recentTitle: {
    color: '#4B4B4B',
    fontWeight: '700',
    fontFamily: 'Muslin',
    fontSize: convertPX(16),
    lineHeight: convertPX(20),
    backgroundColor: '#FBFAFA',
    letterSpacing: convertPX(0.9),
    paddingVertical: convertPX(15),
    paddingHorizontal: convertPX(5),
  },
  recentItem: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    height: convertPX(65),
    paddingHorizontal: '2%',
    justifyContent: 'space-between',
  },
  recentIcon: {
    marginRight: 5,
    width: convertPX(24),
    height: convertPX(24),
  },
  recentText: {
    color: '#4B4B4B',
    fontWeight: '600',
    fontFamily: 'Muslin',
    fontSize: convertPX(14),
    paddingTop: convertPX(5),
    lineHeight: convertPX(18),
    paddingHorizontal: convertPX(5),
  },
  recentSubText: {
    color: '#4B4B4B',
    fontWeight: '400',
    fontFamily: 'Muslin',
    fontSize: convertPX(12),
    lineHeight: convertPX(15),
    paddingVertical: convertPX(2),
    paddingHorizontal: convertPX(5),
  },
  recentAmount: {
    color: '#4B4B4B',
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: 'Muslin',
    height: convertPX(15),
    fontSize: convertPX(15),
    lineHeight: convertPX(15),
    marginVertical: convertPX(18),
    letterSpacing: convertPX(0.9),
  },
  recentBtn: {
    alignItems: 'center',
    height: convertPX(50),
    color: COLORS.primary,
    justifyContent: 'center',
    marginTop: convertPX(12),
    borderRadius: convertPX(6),
    backgroundColor: COLORS.purple,
  },
  recentBtnText: {
    color: COLORS.primary,
    fontSize: convertPX(16),
  },

  projectionWrap: {
    width: convertPX(327),
    height: convertPX(471),
    backgroundColor: '#EDEEF7',
    marginVertical: convertPX(25),
  },
  projectionTitle: {
    color: '#4B4B4B',
    textAlign: 'center',
    fontFamily: 'Muslin',
    fontSize: convertPX(18),
    marginTop: convertPX(15),
    lineHeight: convertPX(29),
    letterSpacing: convertPX(0.9),
    paddingVertical: convertPX(15),
    paddingHorizontal: convertPX(5),
  },
  barchat: {
    width: convertPX(320),
    height: convertPX(197),
    marginTop: convertPX(110),
  },
  text: {
    color: '#000',
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: 'Muslin',
    height: convertPX(18),
    fontSize: convertPX(14),
    lineHeight: convertPX(17.57),
    marginVertical: convertPX(18),
    letterSpacing: convertPX(0.9),
    marginHorizontal: convertPX(20),
  },
});
