import {StyleSheet} from 'react-native';
import {COLORS} from '../../constants/theme';
import {convertPX, height} from '../../utils';

export default StyleSheet.create({
  root: {
    minHeight: height,
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },

  hero: {
    marginTop: 5,
    width: convertPX(326),
    height: convertPX(173),
    borderRadius: convertPX(5),
    backgroundColor: COLORS.purple,
    marginVertical: convertPX(10),
  },

  heroTitle: {
    marginTop: '7%',
    color: '#FFFFFF',
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Muslin',
    height: convertPX(50),
    fontSize: convertPX(40),
    lineHeight: convertPX(50),
    letterSpacing: convertPX(2),
  },
  heroText: {
    marginTop: '1%',
    color: '#FFFFFF',
    textAlign: 'center',
    fontFamily: 'Muslin',
    fontSize: convertPX(16),
    lineHeight: convertPX(20),
    letterSpacing: convertPX(1),
  },
  heroBtn: {
    alignItems: 'center',
    width: convertPX(92),
    height: convertPX(34),
    justifyContent: 'center',
    borderRadius: convertPX(6),
    backgroundColor: COLORS.primary,
  },
  heroBtnText: {
    color: '#4B4B4B',
    textAlign: 'center',
    fontFamily: 'Muslin',
    fontSize: convertPX(12),
    letterSpacing: convertPX(1),
  },
  subtitle: {
    color: '#4B4B4B',
    fontWeight: '500',
    textAlign: 'center',
    fontFamily: 'Muslin',
    height: convertPX(30),
    fontSize: convertPX(20),
    lineHeight: convertPX(30),
    marginVertical: convertPX(5),
    letterSpacing: convertPX(2),
  },
  text: {
    color: '#000',
    fontWeight: '400',
    textAlign: 'center',
    fontFamily: 'Muslin',
    height: convertPX(18),
    fontSize: convertPX(14),
    lineHeight: convertPX(17.57),
    marginVertical: convertPX(18),
    letterSpacing: convertPX(0.9),
    marginHorizontal: convertPX(20),
  },
  fadingContainer: {
    padding: 20,
    backgroundColor: 'powderblue',
  },
  fadingText: {
    fontSize: 28,
  },
  buttonRow: {
    flexBasis: 100,
    justifyContent: 'space-evenly',
    marginVertical: 16,
  },
  dotWrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginVertical: convertPX(10),
  },

  dot: {
    width: convertPX(8),
    height: convertPX(8),
    backgroundColor: COLORS.purple,
    borderColor: COLORS.purple,
    borderWidth: 1,
    borderRadius: convertPX(20),
    marginHorizontal: convertPX(3),
  },
  iconWrap: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    marginVertical: convertPX(20),
    justifyContent: 'space-between',
  },
  icon: {
    width: convertPX(40),
    height: convertPX(40),
  },
  iconText: {
    color: '#000',
    fontWeight: '600',
    fontFamily: 'Muslin',
    height: convertPX(17),
    fontSize: convertPX(12),
    lineHeight: convertPX(15.06),
    marginVertical: convertPX(10),
    letterSpacing: convertPX(0.9),
  },
  options: {
    backgroundColor: '#F4F4F4',
    height: convertPX(270),
    borderRadius: convertPX(6),
    width: convertPX(327),
    marginVertical: convertPX(10),
  },
  recentWrap: {
    width: convertPX(327),
    marginVertical: convertPX(35),
  },
  recentTitle: {
    width: '100%',
    color: '#4B4B4B',
    fontWeight: '700',
    fontFamily: 'Muslin',
    fontSize: convertPX(16),
    lineHeight: convertPX(20),
    backgroundColor: '#FBFAFA',
    paddingVertical: convertPX(15),
    paddingHorizontal: convertPX(5),
  },
  recentText: {
    width: '100%',
    color: '#4B4B4B',
    fontWeight: '600',
    fontFamily: 'Muslin',
    fontSize: convertPX(14),
    paddingTop: convertPX(5),
    lineHeight: convertPX(18),
    paddingHorizontal: convertPX(5),
  },
  recentSubText: {
    // width: '100%',
    color: '#4B4B4B',
    fontWeight: '400',
    fontFamily: 'Muslin',
    fontSize: convertPX(12),
    lineHeight: convertPX(15),
    paddingVertical: convertPX(2),
    paddingHorizontal: convertPX(5),
  },
  checked: {
    marginRight: 5,
    width: convertPX(24),
    height: convertPX(24),
  },
  button: {
    alignItems: 'center',
    width: convertPX(327),
    height: convertPX(50),
    color: COLORS.primary,
    justifyContent: 'center',
    borderRadius: convertPX(6),
    marginTop: convertPX(8),
    backgroundColor: COLORS.purple,
  },
  buttonText: {
    color: COLORS.primary,
    fontSize: convertPX(16),
  },
  projection: {
    height: convertPX(471),
    marginVertical: convertPX(25),
    backgroundColor: '#EDEEF7',
  },
  projectionTitle: {
    width: '100%',
    color: '#4B4B4B',
    textAlign: 'center',
    fontFamily: 'Muslin',
    fontSize: convertPX(18),
    lineHeight: convertPX(29),
    paddingVertical: convertPX(15),
    paddingHorizontal: convertPX(5),
    marginTop: convertPX(15),
    letterSpacing: convertPX(1),
  },
  barchat: {
    marginTop: convertPX(110),
    marginBottom: 0,
    width: convertPX(320),
    height: convertPX(197),
  },
});
